version: '3.8'

services:
    mysql:
        container_name: mysql
        image: mysql:8.0
        command: '--default-authentication-plugin=mysql_native_password && mysqld --init-file="/tmp/database/schema.sql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ecommerce
            MYSQL_USER: ecommerce
            MYSQL_PASSWORD: root
        ports:
            - '4306:3306'
        volumes:
            - ./docker/mysql/:/tmp/database
    php:
        container_name: php
        build:
            context: .
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ecommerce
            DB_USERNAME: ecommerce
            DB_PASSWORD: root
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/ecommerce
        depends_on:
            - mysql
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/ecommerce
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
